### ISSUE TITLE
running miracl example error on 64 bit architecture

### ISSUE THREAD

**Issue by mahima1321** [miracl/MIRACL#100]
I am using miracl-master and trying to run example fuzzy.cpp on Nvdia Jetson nano which is ARM 64 bit architecture. I am facing error running the demo IBE example.
The error is as below:

 
MIRACL error from routine mirsys
              called from your program
Illegal number base

 

I am using mirdef.h as below.

 
/*
 *   MIRACL compiler/hardware definitions - mirdef.h
 *   For C++ build of library
 */

#define MR_LITTLE_ENDIAN
#define MIRACL 64
#define mr_utype long
//#define mr_dltype long
#define mr_unsign64 unsigned long
#define MR_IBITS 32
#define MR_LBITS 64
#define mr_unsign32 unsigned int
//#define MR_FLASH 52
#define MAXBASE ((mr_small)1<<(MIRACL-1))
//#define MAXBASE 4503599627370496.000000
#define MR_NOFULLWIDTH
#define MR_BITSINCHAR 8
//#define MR_NOASM
#define MR_CPP

 
linux64_cpp:

 
rm *.exe
rm *.o
rm miracl.a
cp mirdef.hpp mirdef.h
g++ -c -march=armv8-a -O2 mrcore.c
g++ -c -march=armv8-a -O2 mrarth0.c
g++ -c -march=armv8-a -O2 mrarth1.c
g++ -c -march=armv8-a -O2 mrarth2.c
g++ -c -march=armv8-a -O2 mralloc.c
g++ -c -march=armv8-a -O2 mrsmall.c
g++ -c -march=armv8-a -O2 mrio1.c
g++ -c -march=armv8-a -O2 mrio2.c
g++ -c -march=armv8-a -O2 mrgcd.c
g++ -c -march=armv8-a -O2 mrjack.c
g++ -c -march=armv8-a -O2 mrxgcd.c
g++ -c -march=armv8-a -O2 mrarth3.c
g++ -c -march=armv8-a -O2 mrbits.c
g++ -c -march=armv8-a -O2 mrrand.c
g++ -c -march=armv8-a -O2 mrprime.c
g++ -c -march=armv8-a -O2 mrcrt.c
g++ -c -march=armv8-a -O2 mrscrt.c
g++ -c -march=armv8-a -O2 mrmonty.c
g++ -c -march=armv8-a -O2 mrpower.c
g++ -c -march=armv8-a -O2 mrsroot.c
g++ -c -march=armv8-a -O2 mrcurve.c
g++ -c -march=armv8-a -O2 mrfast.c
g++ -c -march=armv8-a -O2 mrshs.c
g++ -c -march=armv8-a -O2 mrshs256.c
g++ -c -march=armv8-a -O2 mrshs512.c
g++ -c -march=armv8-a -O2 mrsha3.c
g++ -c -march=armv8-a -O2 mrfpe.c
g++ -c -march=armv8-a -O2 mraes.c
g++ -c -march=armv8-a -O2 mrgcm.c
g++ -c -march=armv8-a -O2 mrlucas.c
g++ -c -march=armv8-a -O2 mrzzn2.c
g++ -c -march=armv8-a -O2 mrzzn2b.c
g++ -c -march=armv8-a -O2 mrzzn3.c
g++ -c -march=armv8-a -O2 mrzzn4.c
g++ -c -march=armv8-a -O2 mrecn2.c
g++ -c -march=armv8-a -O2 mrstrong.c
g++ -c -march=armv8-a -O2 mrbrick.c
g++ -c -march=armv8-a -O2 mrebrick.c
g++ -c -march=armv8-a -O2 mrec2m.c
g++ -c -march=armv8-a -O2 mrgf2m.c
g++ -c -march=armv8-a -O2 mrflash.c
g++ -c -march=armv8-a -O2 mrfrnd.c
 
g++ -c -march=armv8-a -O2 mrdouble.c
g++ -c -march=armv8-a -O2 mrround.c
g++ -c -march=armv8-a -O2 mrbuild.c
g++ -c -march=armv8-a -O2 mrflsh1.c
g++ -c -march=armv8-a -O2 mrpi.c
g++ -c -march=armv8-a -O2 mrflsh2.c
g++ -c -march=armv8-a -O2 mrflsh3.c
g++ -c -march=armv8-a -O2 mrflsh4.c
cp mrmuldv.ppc mrmuldv.c
g++ -c -march=armv8-a -O2 mrmuldv.c
g++ -c -march=armv8-a -O2 big.cpp
g++ -c -march=armv8-a -O2 zzn.cpp
g++ -c -march=armv8-a -O2 ecn.cpp
ar rc miracl.a mrcore.o mrarth0.o mrarth1.o mrarth2.o mralloc.o mrsmall.o mrzzn2.o mrzzn3.o
ar r miracl.a mrio1.o mrio2.o mrjack.o mrgcd.o mrxgcd.o mrarth3.o mrbits.o mrecn2.o mrzzn4.o
ar r miracl.a mrrand.o mrprime.o mrcrt.o mrscrt.o mrmonty.o mrcurve.o mrsroot.o mrzzn2b.o
ar r miracl.a mrpower.o mrfast.o mrshs.o mrshs256.o mraes.o mrlucas.o mrstrong.o mrgcm.o
ar r miracl.a mrflash.o mrfrnd.o mrdouble.o mrround.o mrbuild.o
ar r miracl.a mrflsh1.o mrpi.o mrflsh2.o mrflsh3.o mrflsh4.o
ar r miracl.a mrbrick.o mrebrick.o mrec2m.o mrgf2m.o mrmuldv.o mrshs512.o  mrsha3.o mrfpe.o
ar r miracl.a big.o zzn.o ecn.o
rm mr*.o

Please help to run fuzzy IBE example on this platform.

Appreciate your help.

**Comment by mahima1321** [comment]
I resolved this issue

**Comment by kexuedaishu** [comment]
May I ask the solution? I've encountered the same problem. Which mirdef.* you are using? I am on ARM64 system.
