### ISSUE TITLE
Does this library support signature aggregation for BLS12-381 Curve?

### ISSUE THREAD

**Issue by AlexiaChen** [miracl/MIRACL#104]
I juest search source and test , it seems no BLS12-381 Curve and related signature aggregation.

**Comment by mcarrickscott** [comment]
Support for BLS12-381 curves and BLS signature can be found in
https://github.com/miracl/core

Mike

**Comment by AlexiaChen** [comment]
@mcarrickscott   but miracle core does not support signature aggregation like herumi and blst right ? I also create a issue https://github.com/apache/incubator-milagro-crypto-rust/issues/49 on milagro repo before

And I found TestBLS.go https://github.com/miracl/core/blob/master/go/TestBLS.go , there is no signature aggregation feature provided.

**Comment by mcarrickscott** [comment]
Yes, you need to extend the provided code example to do aggregation.

Beware https://eprint.iacr.org/2021/323.pdf

Mike

**Comment by AlexiaChen** [comment]
Thank you for your reply! You provided great information directly to me
