### ISSUE TITLE
How to serialize the cipher(G1,GT) and reload it ?

### ISSUE THREAD

**Issue by bo-hub** [miracl/MIRACL#107]
Is there a way to do serialization in Miracl?  Some  Encryption Systems  like ABE and broadcast encryption the cipher is the elements in G1 or GT.  I want to separate the encryption process and decryption process  in the example program https://github.com/miracl/MIRACL/blob/master/source/curve/pairing/cpabe.cpp  to two program . So I think I should dump the Big object and G1 , GT object to a file in encryption program and reload it in Decryption program . Is there a method in Miracl can do this kind of work.

**Comment by bo-hub** [comment]
i.e How to serialize Big object and G1 ,GT object and deserialize ?

**Comment by mcarrickscott** [comment]
Hello zbo,

The functions "spill " and "restore" perform serialization on the G1, G2
and GT types. For example see bn_pair.cpp line 407.

Mike

**Comment by bo-hub** [comment]
Hi, Michael. 

Thanks for reply.
I have another problem in calling this spill function.
My example code :
```
#include <iostream>
#include <ctime>

#define MR_PAIRING_SSP // AES-80 or AES-128 security GF(p) curve
//#define AES_SECURITY 80   // OR
#define AES_SECURITY 128
//*********************************************
#include "pairing_1.h"

int main(int argc , char** argv){
    PFC pfc(AES_SECURITY);

    time_t seed;
    time(&seed);

    Big alpha;
    G1 g;
    pfc.random(g);
    pfc.random(alpha);
    
    //save process
    int len;
    char* bytes;
    //pfc.precomp_for_pairing(g);
    len = pfc.spill(g,bytes);
    printf("len of bytes : %d \n",len);
    printf("bytes:\n");
    for(int i = 0; i<len; ++i){
         printf("%.2X",bytes[i]);
    }
    return 0;
}
```

If I do not add `pfc.precomp_for_pairing(g)` , then the output of length is 0 . If add the  `pfc.precomp_for_pairing(g)` ,the length is 98688. I guess the function of precomp is to precomputing some values of g^1,g^2,g^3 ... so we can do calculation quickly laterly. It is reasonable when doing encryption. But in the exporting private key process, Why can not just save an element for more short key size ? Since the precomputing work can also be done by the decryptor.   Am I missing something? I know some abstract concepts of pairing but no idea the implementation details.

**Comment by bo-hub** [comment]
By the way , Is Big also serializable?

**Comment by bo-hub** [comment]
By calling `sizeof(G1)`,  It is 40 bytes. Could we JUST save the 40 bytes and reload it ?

**Comment by mcarrickscott** [comment]
You can use the functions to_binary() and from_binary(). See comments in
big.h

Mike

**Comment by bo-hub** [comment]
> Hi, Michael.
> 
> Thanks for reply. I have another problem in calling this spill function. My example code :
> 
> ```
> #include <iostream>
> #include <ctime>
> 
> #define MR_PAIRING_SSP // AES-80 or AES-128 security GF(p) curve
> //#define AES_SECURITY 80   // OR
> #define AES_SECURITY 128
> //*********************************************
> #include "pairing_1.h"
> 
> int main(int argc , char** argv){
>     PFC pfc(AES_SECURITY);
> 
>     time_t seed;
>     time(&seed);
> 
>     Big alpha;
>     G1 g;
>     pfc.random(g);
>     pfc.random(alpha);
>     
>     //save process
>     int len;
>     char* bytes;
>     //pfc.precomp_for_pairing(g);
>     len = pfc.spill(g,bytes);
>     printf("len of bytes : %d \n",len);
>     printf("bytes:\n");
>     for(int i = 0; i<len; ++i){
>          printf("%.2X",bytes[i]);
>     }
>     return 0;
> }
> ```
> 
> If I do not add `pfc.precomp_for_pairing(g)` , then the output of length is 0 . If add the `pfc.precomp_for_pairing(g)` ,the length is 98688. I guess the function of precomp is to precomputing some values of g^1,g^2,g^3 ... so we can do calculation quickly laterly. It is reasonable when doing encryption. But in the exporting private key process, Why can not just save an element for more short key size ? Since the precomputing work can also be done by the decryptor. Am I missing something? I know some abstract concepts of pairing but no idea the implementation details.

Hello Michael,  
I checked the comments in big.h, already know how to do this work for Big object.  
But still don't understand why spill function should save the precomputation of  `G1`  to bytes array?  Could we just save `G1` ?

**Comment by HuangMinming** [comment]
Is there any solution about how to do serialization for G1,G2,GT?
