### ISSUE TITLE
build in Intel SGX

### ISSUE THREAD

**Issue by HuangMinming** [miracl/MIRACL#131]
Hi, I want to build MIRACL with intel sgx sdk[https://github.com/intel/linux-sgx], not libc. But there was a error in mrgf2m.c which needs xmmintrin.h. In fact sgx sdk doesn't provide such header file. 
Is there any solution to this problem. Is there an Macro which can avoid to use xmmintrin.h. Thanks.
I compile the code with "-DMR_NO_FILE_IO -DMR_NO_STANDARD_IO -nostdinc -I/opt/intel/sgxsdk/include -I/opt/intel/sgxsdk/include/tlibc -I/opt/intel/sgxsdk/include/libcxx". 
Inter SGX SDK was installed in "/opt/intel/sgxsdk/include"

**Comment by mcarrickscott** [comment]
If the Intel enclave does not support these extensions (and I am not
familiar with its capabilities) then you need to edit mrgf2m.c so that it
just uses the standard C code.

Mike

**Comment by HuangMinming** [comment]
Thanks for you reply. I will try to edit mrgf2m.c
