### ISSUE TITLE
Default Algorithm for multi-precision field multiplication ? 

### ISSUE THREAD

**Issue by SNBasti** [miracl/MIRACL#17]
Hi, 

I am setting up an Elliptic Curve Cryptography system and I try to figure out what default algorithm the MIRACL-Library uses for the underyling field multiplication in the finite field ? 

The appropriate function is : 

void multiply(_MIPD_ big x, big y, big z)

But I can't figure out the algorithm just by looking at the code.

Thanks in advance

**Comment by mcarrickscott** [comment]
I guess you are talking about the calculation of x*y mod p, where p is
prime. For elliptic curve crypto the multiplication to calculate x*y  is
carried out using the standard school-boy method. Then Montgomery's method
for modular reduction without trial division is used, to reduce modulo p.

If the modulus is a pseudo-mersenne or generalized mersenne special fast
code can be used, enabled by definitions inserted into mirdef.h

But Montgomery's method is the default, which was your question. Note for
this method to work all residues must first be transformed to n-residue
format.

See https://cseweb.ucsd.edu/classes/fa06/cse246/montgomery.pdf


Mike

**Comment by SNBasti** [comment]
Thanks for the fast and good response !
