### ISSUE TITLE
Bug in precomputations spill and restore

### ISSUE THREAD

**Issue by baz1** [miracl/MIRACL#26]
Hello again,

I found a new problem in the BN implementation of pairing_3.h (that might also exist in other instantiations):
```
#include <iostream>

#define MR_PAIRING_BN
#define AES_SECURITY 128
#include "pairing_3.h"

using namespace std;

int main() {
    PFC pfc(AES_SECURITY);
    G1 a, b;
    Big c = pfc.hash_to_group("hi");
    char *data;
    pfc.hash_and_map(a, "hello");

    /* Copying a to b with precomputations */
    b = a;
    pfc.precomp_for_mult(a);
    a.spill(data);
    b.restore(data);

    if (a != b)
        cout << "a != b" << endl; // Not displayed
    if (pfc.mult(a, c) != pfc.mult(b, c))
        cout << "problem" << endl; // Displayed
    return 0;
}
```
It seems that it comes from the fact that the `mtbits` variable in G1 is not updated after the restore.
Note that this problem also occurs in G2 and GT for similar reasons.
Putting the value of `mtbits` - or just the `small` boolean value - in the data to restore it afterwards would solve the problem.
Best,

Rémi

**Comment by mcarrickscott** [comment]
Yes, that's a bug. Simple fix as you say is to put mtbits at the end of the
spill, and restore it from there.

I'll put it in the backlog..


Mike
