### ISSUE TITLE
SHA secret key problem

### ISSUE THREAD

**Issue by baicaihenxiao** [miracl/MIRACL#33]
I know how to use SHA256 to handle a string like this:

    char s[HASH_LEN];
    sha256 sh;

    shs256_init(&sh);

    for (i=0;;i++)
    {
        if (string[i]==0) break;
        shs256_process(&sh,string[i]);
    }
    shs256_hash(&sh,s);
But I don't know how to set the SHA256' secret key,  whether can I set it in the program?
Thank you very much for any help

**Comment by mcarrickscott** [comment]
Hello,

Sha256 is a one way hash function. It does not have a secret key,

Mike

**Comment by baicaihenxiao** [comment]
Thank you, I think I have confused HMAC and SHA.
