### ISSUE TITLE
Build problem: -m64 option not supported on Arm

### ISSUE THREAD

**Issue by HasseM** [miracl/MIRACL#35]
I am trying to get Scapi to work on my Raspberry Pi3 (Arm). Scapi uses Miracl library in their build process. This proces fails on Miracl with the following error:

```
make[1]: Entering directory '/home/pi/scapi'
Copying the miracl source files into the miracl build dir...
make[1]: Leaving directory '/home/pi/scapi'
Compiling the Miracl library (C)...
make[1]: Entering directory '/home/pi/scapi/build/Miracl'
cp 32bit/c/mirdef.h mirdef.h
gcc -fPIC -m64 -O2 -c mrcore.c
gcc: error: unrecognized command line option ‘-m64’
makefile:60: recipe for target 'mrcore.o' failed
make[1]: *** [mrcore.o] Error 1
make[1]: Leaving directory '/home/pi/scapi/build/Miracl'
makefile:142: recipe for target 'compile-miracl' failed
make: *** [compile-miracl] Error 2
pi@raspberrypi:~/scapi $
```

Obviously -m64 (and -m32) is not supported on Arm.....

Is there an easy way to fix this? I tried removing the -m64 option, but then it fails at a later stage. Note that I m not using miracl directly, but it's part of the Scapi package that I try to install.

**Comment by mcarrickscott** [comment]
Despite having a 64 bit processor, the pi 3 can only run 32 bit apps, under
its 32-bit operating system. To run 64-bit arm code, you would need a
pi clone like the odroid c2.

To build miracl, I don't know what your scapi make file is doing. I suggest
you just use the normal miracl build process (bash doit)

Mike

**Comment by HasseM** [comment]
I was just following an example that uses scapi. Scapi is using miracl. And I guess that the process now becomes to modify scapy makefile and get indept knowledge about the miracl build process. Thats a pretty nice challenge for someone with limited knowledge of the linux system. Do you happen to know a step by step tutorial for setting up miracl 32 bit on a Arm (RPi3)?

**Comment by mcarrickscott** [comment]
There is a step-by-step description of the Linux build process for MIRACL
in the file first.txt

There are just two steps...


Mike
