### ISSUE TITLE
Segmentation fault when executing pairing function

### ISSUE THREAD

**Issue by teffygithub** [miracl/MIRACL#38]
Hello, I want to run ake12bnx.cpp in pairing document folder for example. It can be compiled successfully. But when running, it reports segmentation fault. After checking, I find the fault occurs at the function "set_frobenius_constant". I don't know how to solve it. Can you help me?

**Comment by mcarrickscott** [comment]
Sure, but you have to give us more details. What processor, what compiler,
and what mirdef.h file are you using?


Mike Scott

**Comment by teffygithub** [comment]
Pentium(R) Dual-Core  CPU, g++ compiler, linux 32-bit, the annotation in mirdef.h is
/* 
 *   MIRACL compiler/hardware definitions - mirdef.h
 *   This version suitable for use with most 32-bit computers
 *   e.g. 80386+ PC, VAX, ARM etc. Assembly language versions of muldiv,
 *   muldvm, muldvd and muldvd2 will be necessary. See mrmuldv.any 
 *
 *   Also suitable for DJGPP GNU C Compiler
 *   ... but change __int64 to long long
 */

**Comment by mcarrickscott** [comment]
That seems fine.

How are you building the MIRACL library?

Are you following the instructions in first,txt for a 32-bit build?

Are you building the application exactly like this?

C:\miracl>g++ -O2 ake12bnx.cpp zzn12a.cpp zzn4.cpp ecn2.cpp zzn2.cpp
big.cpp zzn.cpp ecn.cpp miracl.a -o ake12bnx


Mike

**Comment by teffygithub** [comment]
The order in ake12bnx.cpp is like this
g++ -O2 -DZZNS=4  ake12bnx.cpp zzn12a.cpp zzn4.cpp ecn2.cpp zzn2.cpp big.cpp zzn.cpp ecn.cpp miracl.a -o ake12bnx

Now, I removed "-DZZNS=4". The program can be run successfully.

Thank you for your help!
