### ISSUE TITLE
Is the implementation of BPS FPE compliant to NIST Special Publication 800-38G?

### ISSUE THREAD

**Issue by rafaelsales** [miracl/MIRACL#39]
Publication from March, 2016: https://www.nist.gov/news-events/news/2016/03/new-nist-security-standard-can-protect-credit-cards-health-information

Specification in NIST Special Publication 800-38G: http://dx.doi.org/10.6028/NIST.SP.800-38G

Implementation of FF3 in MIRACL: https://github.com/miracl/MIRACL/blob/master/source/mrfpe.c

**Comment by mcarrickscott** [comment]
Yes. See
http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/FF3samples.pdf

Mike Scott

**Comment by rafaelsales** [comment]
Thanks!
