### ISSUE TITLE
Question about bilinearity of pairing

### ISSUE THREAD

**Issue by SysFlat** [miracl/MIRACL#40]
Hi,

We have completed the implementation of R-ate and now we are verifying its correctness. But we find that once we modify the parameters in the file , it can not meet the properties of  bilinearity. Can you give me some advices? 
### Parameters in our implementation
 Our parameters are set in advance. They just like this:

- BN curve: y^2= x^3+b,**b=5**
- Tower extension :1-2-4-12
![default](https://cloud.githubusercontent.com/assets/19515782/21050440/bf54133c-be55-11e6-9b53-3dc5aeacf360.png)
- The characteristic p of the prime field, the group order r, and the trace of Frobenius t_r of the curve are parametrized as follows:
![default](https://cloud.githubusercontent.com/assets/19515782/21050489/efdad252-be55-11e6-9951-451633c4432b.png)
We can easily find that our parameters are quiet similar except t and b. 

### problem

  we set the point P and Q to a constant value and modify parameter t and b in in ake12bnx.cpp.**Then our result are the same.** But we find that it can not meet the properties of bilinearity of the R-ate Pairing. In fact ,we find 
![default](https://cloud.githubusercontent.com/assets/19515782/21050715/532a2744-be57-11e6-80d2-01cb4cba0359.png)
in this case.

However, it meets the properties of bilinearity perfectly if we just use the original parameters in your file.
That is to say, we will go wrong if we modify the parameters in your file.

I wonder if there exists some combination between t and b ?Or any other reasons ?Can you give me some advices?

 Thank you!

**Comment by mcarrickscott** [comment]
Hello,

Problem could be (a) the sign of t, or (b) whether the twist is M-type or
D-type.

How did you find this curve? Did you use the bin.cpp program?


Mike Scott

**Comment by mcarrickscott** [comment]
That should be bn.cpp

Mike

**Comment by SysFlat** [comment]
Thanks for your reply.

Our twist is **D-type: y^2= x^3+b/ε**.
And I never used bn.cpp file to generate bn curve. The parameters of the encryption system are given in advance. In a word, the parameters mentioned above are the standard set by some agencies and we just use them to implement this encryption system. Also we can not modify them . If so, are there some problems with these parameters?

Thanks in advance.

**Comment by mcarrickscott** [comment]
OK, I see the problem. In fact your twist is M-type


Mike Scott

**Comment by SysFlat** [comment]
### Thanks very much!!!


It is great! I have change twist to M-type and It works perfectly! Your reply is very useful to me. Also I read your paper “**A note on twists for pairing friendly curves**” carefully. But I still confuse about how to select twist type according to the parameters . In the third chapter(**Using sextic twists for pairings**) of your note, you write this:
![default](https://cloud.githubusercontent.com/assets/19515782/21091775/58dd02a0-c083-11e6-9f18-86e2ab5a01b9.png)


Is it mean that we can just use another type if we get wrong in one type? Whether there is a kind of method can be quantified to select the appropriate twist type ? Or any other thing? Can you give some advice?

Look forward to your reply.
Thanks in advance!

**Comment by mcarrickscott** [comment]
Hello,

Glad to hear that it worked! For more insights you should examine the
bn.cpp code....

Sorry, I cannot provide any further help.

Mike

**Comment by SysFlat** [comment]
oh,that`s all right.

In fact ,your help is of great significance to me.You are a kind person.Thanks again for your kind help.

Best wishes to you!
