### ISSUE TITLE
Any guide for use the library on Android?

### ISSUE THREAD

**Issue by YangRongAtGit** [miracl/MIRACL#45]
Anywhere I could find a guide about use the library on android? Thanks

**Comment by YangRongAtGit** [comment]
environment
The target android SDK version is 25
android studio version 2.3

I tried both version of the mrmuldv.c
the 32 bit version has following error
Error:(76, 7) error: unknown register name 'rax' in asm

the amd64 version has following error
Error:(21, 7) error: unknown register name 'eax' in asm

**Comment by mcarrickscott** [comment]
Hello,

Problem here is that you are attempting to build for an Intel x86 target,
whereas your processor is probably an ARM. Its probably best not to start
with any assembly language.

Best to start with a standard C build of the library.

Mike

**Comment by YangRongAtGit** [comment]
Hello Mike,
The error is from mrmuldv.c which is renamed from mrmuldv.g64. It is in the MIRACL library.  I will edit my comment to make it clear.

Thanks

**Comment by mcarrickscott** [comment]
Sure, but that file contains in-line assembly language. You need to rename
mrmuldv.ccc to mrmuldv.c

Alternatively follow instructions in ARM.TXT


Mike

**Comment by npj008** [comment]
@YangRongAtGit Can you tell me steps to use this library in android project. I am very much new to android so. Thanks in advance.

**Comment by mcarrickscott** [comment]
Sorry, I have no experience of using MIRACL with Android. However as I
indicated it can be configured as a pure C library.

So its just programming...


Mike

**Comment by YangRongAtGit** [comment]
For the developers who is using android studio 2.3 here is the CMake file for MIRACL 

set (MIRACLE_SOURCE_DIR src/main/cpp/miracl/)

include_directories(${MIRACLE_HEADER_DIR})

file(GLOB MIRACLE_HEADER_FILES ${MIRACLE_SOURCE_DIR}/*.h)
file(GLOB MIRACLE_SOURCE_FILES ${MIRACLE_SOURCE_DIR}/*.c)

add_library( # Sets the name of the library.
             mrc-lib

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             src/main/cpp/mrc-lib.cpp
             ${MIRACLE_HEADER_FILES}
             ${MIRACLE_SOURCE_FILES}
             )

find_library(log-lib log)

target_link_libraries(
                       mrc-lib
                       ${log-lib} )

**Comment by YangRongAtGit** [comment]
Another thing is it seems google fixed the bug mentioned in the ARM.txt.
I run a test in the glue function as the doc stated:
```
    unsigned long long x;
    unsigned long a,b;
    a=0;
    b=0xFFFFFFFF;
    x=(unsigned long long)a-b;
```

The result is :
```
(lldb) p x
(unsigned long long) $1 = 18446744069414584321
(lldb) p/x x
(unsigned long long) $2 = 0xffffffff00000001
```

**Comment by YangRongAtGit** [comment]
@npj008 I am not a expert of android studio 2.3. By some reason I really dislike Java. Although I spent all my time in uni using Java as my main programming language. Anyway, the way I integrate MIRACL into an android studio 2.3 project is:
1. New project, tick the option 'Include C++ support' in the first wizard page.
2. In the last step of the wizard, make sure the C++ standard is 'Toolchain Default' (C11 might works I just didn't test). I hate exceptions, so no exception used in the project. rtti is slow, so rtti is out as well.
3. A default shared c library (native-lib) will be generated after you click the button 'Finish'
4. If you want to modify the name of the library and the generated cpp file (native-lib.cpp), you need to do:
    4.1 Right click the cpp file -> In the popup menu, select 'Refactor' -> 'Rename'
    4.2 Find the CMake file. When you use the 'Android' view, the cmake file is under the folder 'External Build files'. 
5. Copy the MIRACL header / source files mentioned in the ARM.txt to where ever you want. Or just use the MIRACL default repository by changing the value of 'MIRACLE_SOURCE_DIR' in CMake  .
6. In the android studio, click build -> Refresh Linked C++ Projects
8. Click the button 'Sync project with Gradle Files'. (Should not need this since the Gradle stuff is not been touched but I had strange problem fixed by sync gradle files).
9. Clean & rebuild-> RUN

**Comment by npj008** [comment]
Thanks for your super steps. I will try your step today. If you have any working demo project of android studio, then please attach at joshinikunj008 at gmaiel dot com
Thank you...

**Comment by simeon-aladjem** [comment]
You might want to take a look at https://github.com/miracl/incubator-milagro-mfa-sdk-android.
It is an Android SDK that wraps some crypto functionality. The crypto lib is not `MIRACL`, but its successor, but in any case you can see how the C/C++ code is wrapped in an Android/Java code.
It also builds with Android Studio, so it will be helpful for you.
