### ISSUE TITLE
Errors in Miracl installation in MAC OS X - Updated with Steps [SOLVED]

### ISSUE THREAD

**Issue by npj008** [miracl/MIRACL#46]
hello,
I am trying to install miracl in OSX from this link **https://github.com/jkhoury/MIRACL/blob/enhancement-1/README-makefile.txt** 

When I try to generate KSS curve (Line number 39) in link, I am getting error of  
**error: use of undeclared identifier 'to_binary'
                to_binary(y,bytes_per_big,&bytes[j],TRUE);**

Help please, how to solve it. Because I am trying to install java version of miracl from this link
https://dsl-external.bbn.com/tracsvr/openP3S/wiki/jmiracl

But as of now, I am not able to generate library for kss curve, I am stuck.

Please help.

Thanks.
![screen shot 2017-03-31 at 8 15 40 pm](https://cloud.githubusercontent.com/assets/8158297/24555609/730ec04c-164f-11e7-9e55-0f1c470eab59.png)

**Comment by mcarrickscott** [comment]
Check that you are using the correct big.h and big.cpp.

The function to_binary() is declared there. Make sure you are using the
correct version of *both* files


Mike

**Comment by npj008** [comment]
@mcarrickscott Yes mike,
I am using updated version of big.cpp , big.h, zzn.cpp, zzn.h 
There is no error for other types of curves cp,mnt,bn,bls.
only when I try to generate for kss type, its throwing that error. If my both files are wrong then it must not work for other types of curve also.


thanks.

**Comment by npj008** [comment]
@mcarrickscott Have a look at this snippet. For bls_pair.cpp it is not generating error. but for kss_pair.cpp it is generating error. Please help, I am not getting, what is wrong.

![screen shot 2017-03-31 at 9 57 37 pm](https://cloud.githubusercontent.com/assets/8158297/24559707/50139906-165d-11e7-9310-3e2b8ede9991.png)

**Comment by mcarrickscott** [comment]
That is strange.

to_binary(x,bytes_per_big,&bytes[j],TRUE);

Here x should be a Big, not a ZZn. The compiler should automatically apply
the cast, but maybe it has not.

So try

to_binary(Big(x),bytes_per_big,&bytes[j],TRUE);


Mike

**Comment by npj008** [comment]
@mcarrickscott Thanks, that was exactly problem of type casting. Here is the updated file for future geeks. :) 
[kss_pair.cpp.zip](https://github.com/miracl/MIRACL/files/886437/kss_pair.cpp.zip)

**Comment by mcarrickscott** [comment]
Great, and thanks..

Mike

**Comment by npj008** [comment]
@mcarrickscott I hope you will help and dont mind. I am asking too much question, but now I am facing other error when I execute **make benchmarkthread curve=<curve>** for any type of curve either bls,bn,kss,mnt,cp. I am getting similar type of error.. have a look please.
Thanks in advance.

![screen shot 2017-03-31 at 10 42 39 pm](https://cloud.githubusercontent.com/assets/8158297/24561225/9a099e60-1663-11e7-97c7-01a99e2192ba.png)

And when I try **make cpabe curve=<curve> comba=n** for any type of curve, I am getting this error.
![screen shot 2017-03-31 at 10 45 59 pm](https://cloud.githubusercontent.com/assets/8158297/24561294/d34256f4-1663-11e7-9495-ee0136ed6647.png)

 
Thank you so much @mcarrickscott  in advance.

**Comment by mcarrickscott** [comment]
Sorry, benchmarkthread.cpp is not a MIRACL file, we do not recognize it.

Variable length arrays (like g2[n]) require C99 support, which sometimes
requires the gcc flag -std=C99

Undeclared identifiers should be easy to detect.

Mike

**Comment by npj008** [comment]
@mcarrickscott Thank you for help.

**Comment by npj008** [comment]
# **The steps for MAC OS X user to install Miracl**

1. Make sure you have installed XCode, maven 3, and jdk 1.6 or later.
2. Download https://github.com/jkhoury/MIRACL/tree/enhancement-1
3. **unzip -j -aa -L miracl.zip**
4. Replace Attached zip files content with Extracted folder of miracl.
5. Grant root access to PWD, if not granted.
6. **$make clean** (If it is executed first time, it will give error. - Not an issue :) )
7. **$make clean**
8. **$make curve=cp
    $make curve=mnt
    $make curve=bn
    $make curve=kss
    $make curve=bls**
9. **sudo make install curve=cp** repeat this for each type of curve.

For more detail please folow **https://github.com/jkhoury/MIRACL/blob/enhancement-1/README-makefile.txt**
[Replace_Files.zip](https://github.com/miracl/MIRACL/files/886503/Replace_Files.zip)

Special Thanks to @mcarrickscott .
