### ISSUE TITLE
bls/BN pairing example segfaults 

### ISSUE THREAD

**Issue by taybart** [miracl/MIRACL#73]
Hello, 
When I use the provided example of [bls.cpp](https://github.com/miracl/MIRACL/blob/master/source/curve/pairing/bls.cpp). There is a segfault that I have traced to the destructor of PFC. Am I missing something? What is being destructed that doesn't exist?
Thanks,
taybart

**Comment by taybart** [comment]
I left out build info, sorry about that. 
compiler: 
```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
MIRACL version:  `4bd13901519d329c6c1369fb3322b52fe10c7a6e`

**Comment by mcarrickscott** [comment]
I tried this here, and it worked.

Marys-Mac-mini:miracl michaelscott$ g++ -O2 bls.cpp bn_pair.cpp zzn12a.cpp ecn2.cpp zzn4.cpp zzn2.cpp big.cpp zzn.cpp ecn.cpp miracl.a -o bls
Marys-Mac-mini:miracl michaelscott$ ./bls
Signature= 1 2391EC1607AFD3215E7397071F4EC6F6004868FC0A5DA0D01F0FB31CDDFC824B
Signature verifies
Marys-Mac-mini:miracl michaelscott$ ./bls
Signature= 1 20848B8D7448F02400BC5CED5170B3826BF7B0AFBB5A1BB8057DB73F917534B3
Signature verifies
Marys-Mac-mini:miracl michaelscott$

Mike

**Comment by mcarrickscott** [comment]
This was built using a library built with this mired.h file

/*
 *   MIRACL compiler/hardware definitions - mirdef.h
 */

#define MR_LITTLE_ENDIAN
#define MIRACL 64
#define mr_utype long
#define mr_unsign64 unsigned long
#define MR_IBITS 32
#define MR_LBITS 64
#define mr_unsign32 unsigned int
#define MR_FLASH 52
#define MAXBASE ((mr_small)1<<(MIRACL-1))
#define MR_BITSINCHAR 8


Mike

**Comment by mcarrickscott** [comment]
This also works using clang instead of g++

Marys-Mac-mini:miracl michaelscott$ clang++ -O2 bls.cpp bn_pair.cpp zzn12a.cpp ecn2.cpp zzn4.cpp zzn2.cpp big.cpp zzn.cpp ecn.cpp miracl.a -o bls
Marys-Mac-mini:miracl michaelscott$ ./bls
Signature= 0 8A0F9AE1C82A8B2903518997E295DB5C91EB64FA0D4BF0974ECA55685A77B9A
Signature verifies
Marys-Mac-mini:miracl michaelscott$ ./bls
Signature= 1 23782C339AB3DC4C7A5E1E9E00023DFBBA9C359987AFDC8296B8D1A3D5DCC20E
Signature verifies
Marys-Mac-mini:miracl michaelscott$ ./bls
Signature= 0 19D757E82BD8F127AA28E925EAB13888F5D0D5DEE2D72412CB93829FFEA1EDA0
Signature verifies
Marys-Mac-mini:miracl michaelscott$ 

So I am unable to reproduce the problem here...

Mike

**Comment by taybart** [comment]
OK, I figured it out. I was trying out different functionality of MIRACL in the same file. When I include the line: 

`Miracl precision(50, MAXBASE);`

This is what was causing the segfault, I am still not exactly sure why (name clash?). 

@mcarrickscott those examples did actually work for me, thanks that helped me get that line isolated.

**Comment by khadouja04** [comment]
i used the bls solution for ecn3 type key generation and this solution uses the mnt curve, but my problem is for asymmetric decryption i can not find a model working on this curve, someone can help me.

**Comment by mcarrickscott** [comment]
Would like to help, but don't understand the question. What method for
asymmetric decryption are you referring to, and what model are you looking
for?

Mike

**Comment by khadouja04** [comment]
Hello

I used the bls solution to generate the keys that uses as mnt curve,
I need asymmetric encryption to encrypt the exchange between th nodes with
these generated  keys (type ecn3).
My problem is that I can not find a model aes that uses the mnt curve with
the type of keys is ecn3, zzn3.

I hope that helps me,

thank you in advance

Best regards

Le mar. 12 mars 2019 à 17:05, Michael Scott <notifications@github.com> a
écrit :

**Comment by mcarrickscott** [comment]
Seems like you want to hash an ecn3 value to an AES key?

In mnt_pair.cpp there are functions

start_hash()
add_to_hash()
finish_hash()

These can be used to hash a G2 values (ecn3 in this case) to a Big number
which can be used as an AES key.

Mike

**Comment by khadouja04** [comment]
hi

Le mar 26 mars 2019 21:08, Taylor Bartlett <notifications@github.com> a
écrit :
