### ISSUE TITLE
Examples on using elliptic curves

### ISSUE THREAD

**Issue by vusirikala** [miracl/MIRACL#77]
I am planning to implement a scheme using elliptic curves using NIST P-xxx elliptic curves. I am searching for examples on how to use MIRACL library but couldn't find any. Please provide sample code on MIRACL library for the following operations

(1) Initialize any standard NIST prime order field curve

(2) Sample a random point or generator on the curve

(3) Sample a random integer in range [1, order of curve]

(4) Perform group operation, exponentiation

Also please provide the header files that I need to include in my code.

**Comment by mcarrickscott** [comment]
Hello,

In fact such a program is provided in the distribution - ecsgen.cpp

This is a very short program.

The data for the NIST curves are provided in the files

secp160.ecs
secp192.ecs
secp224.ecs
secp256.ecs
secp384.ecs
secp521.ecs

Copy the one of your choice to common.ecs

Then compile the ecsgen program by, for example

g++ -O2 ecsgen.cpp ecn.cpp big.cpp miracl.a -o ecsgen

When you run the program it does all of the steps that you require, as can
be seen from the source code in ecsgen.cpp

Mike
