### ISSUE TITLE
Integer operation attempted on Flash number

### ISSUE THREAD

**Issue by vusirikala** [miracl/MIRACL#78]
I am trying to run the following simple code.
```
 ifstream common("secp192.ecs");    /* construct file I/O streams */
 int bits,ep;
 miracl *mip=&precision;

    ECn G,W;
    Big a,b,p,q,x,y,d;
    long seed=345123567;
    irand(seed);

    common >> bits;
    mip->IOBASE=16;
    common >> p >> a >> b >> q >> x >> y;
    mip->IOBASE=10;

    ecurve(a,b,p,MR_PROJECTIVE);

    if (!G.set(x,y))
    {
        cout << "Problem - point (x,y) is not on the curve" << endl;
        return 0;
    }


    int count = 10000;
    int count2 = 4096;
   	Big exponents[count];
   	ECn generators[count];

   	for (int i = 0; i < count; i++)
   		exponents[i] = rand(q);

   	for (int i = 0; i < count; i++)
   		generators[i] = exponents[i] * G;

   	mul(count2, exponents, generators);
```
It shows this error. 

```
MIRACL error from routine multiply
              called from nres_modmult
              called from ecurve_add
              called from ecurve_multn
              called from your program
Integer operation attempted on Flash number
```
Please help me out!

**Comment by mcarrickscott** [comment]
Hello,

OK, there are two problems with your code. First you have not initialized
the generator G.

Second the function mul() will not work with a large first parameter, as
internally it requires storage of 2^4096, which is way too much.

So try this code...


 ifstream common("secp192.ecs");    /* construct file I/O streams */
  int bits,ep;
  miracl *mip=&precision;

    ECn G,W;
    Big a,b,p,q,x,y,d;
    long seed=345123567;

    common >> bits;
    mip->IOBASE=16;
    common >> p >> a >> b >> q >> x >> y;
    mip->IOBASE=10;

    ecurve(a,b,p,MR_PROJECTIVE);

    if (!G.set(x,y))
    {
        cout << "Problem - point (x,y) is not on the curve" << endl;
        return 0;
    }

    int count = 10000;
    int count2 = 4096;
    Big exponents[count];
    ECn generators[count];

    for (int i = 0; i < count; i++)
         exponents[i] = rand(q);

    for (int i = 0; i < count; i++)
         generators[i] = exponents[i] * G;

    cout << "Ready to go" << endl;

   for (int i=0;i<count2;i+=8)
        W+=mul(8,&exponents[i],&generators[i]);

    cout << "W= " << W << endl;
    //mul(count2, exponents, generators);
    return 0;


Mike
