### ISSUE TITLE
Speeding up pfc multi_pairing

### ISSUE THREAD

**Issue by iesiyok** [miracl/MIRACL#83]
Hello,

I am using MIRACL for some elliptic curve cryptography operations, I benchmarked and noticed that using BLS pairing, pfc.multi_pairing(2, g2, g1) is taking a large amount of time. I am wondering if I missed any steps or is there anything that I could speed this up? 
This single operation takes around 120ms on my computer with precomp_for_pairing(g2). 
Without the precomputation it is around 170ms.

For example, BLS short signature example here : https://github.com/miracl/MIRACL/blob/4bd13901519d329c6c1369fb3322b52fe10c7a6e/source/curve/pairing/bls.cpp

Best wishes,
Ilkan

**Comment by mcarrickscott** [comment]
Hello Ilkan,

Using the BLS.CPP example program with the BN curve at the AES-128 level it
takes about 7ms on my PC (x64 i586 3GHz).

So maybe its your computer, or you are using a higher security curve?

Mike

**Comment by iesiyok** [comment]
No, you need to use BLS curve with AES-256 level

**Comment by mcarrickscott** [comment]
Ah well in that case it takes about 80ms on my PC. I'm afraid that at
higher security levels it just takes a lot longer. The final
exponentiations scale as O(n^3), so the larger modulus size blows up the
execution time.

For somewhat faster production code try https://github.com/miracl/core


Mike

**Comment by iesiyok** [comment]
Okay thank you very much and I will try the miracl/core.
