### ISSUE TITLE
Base must be binary

### ISSUE THREAD

**Issue by CaptainLazarus** [miracl/MIRACL#87]
After following all the instruction for installing miracl , I tried running the first sample program for testing and have gotten the following error.
`
MIRACL error from routine mirsys
              called from your program
Base must be binary (MR_ALWAYS_BINARY defined in mirdef.h ?)
`

Any idea where I went wrong?

The sample program I'm talking about 

```
#include <stdio.h>
#include "miracl.h"
/* include MIRACL system */

void main()
{ /* calculate factorial of number */
    big nf;
    /* declare "big" variable nf */
    int n;
    miracl *mip=mirsys(5000,10);

    // nf=mirvar(1);

    printf("factorial program\n");
    printf("input number n= \n");
    scanf("%d",&n);
    getchar();
    
    while (n>1)
        premult(nf,n--,nf);

    printf("n!= \n");
    otnum(nf,stdout); /* output result */

}
```

**Comment by mcarrickscott** [comment]
Hello,

It works fine here... It is most likely, as the error message suggests)
that your mirder.h file has been modified

Mike

**Comment by CaptainLazarus** [comment]
I followed the instructions given by config.c and changed the generated mirdef.lst to mirdef.h. After that I didn't change anything. Any solutions?

**Comment by mcarrickscott** [comment]
Ah, OK so you did change mirdef.h

That is the cause of the problem.

Copy mirdef.h64 to mirdef.h and try again

Mike

**Comment by mcarrickscott** [comment]
After you copy mirdef.h64 to mirdef.h, don't forget to rebuild the library.

Mike

**Comment by CaptainLazarus** [comment]
Seemed to work. Thanks :)
