### ISSUE TITLE
error in function mr_xor()

### ISSUE THREAD

**Issue by HuangWen92** [miracl/MIRACL#94]
There is an error when I run the code as following. How can I fix it when I want to use the operation of xor.  Thank you very much for your help.

for (int i = 0; i < 1000; i++) {
		big num1 = mirvar(0);
		big num2 = mirvar(0);
		big num3 = mirvar(0);
		big num4 = mirvar(0);
		bigrand(q,num1);
		bigrand(q, num2);
		mr_xor(num1, num2, num3);
		mr_xor(num3, num2, num4); 
		printf("the i:%d\n");
		if (fcomp(num1, num4) != 0)printf(" there is an error in xor\n");
			   
	}
![image](https://user-images.githubusercontent.com/5373633/103170466-65bf1480-487f-11eb-8319-703b545d7202.png)

**Comment by mcarrickscott** [comment]
Sorry, unable to reproduce here.

What is your q?

Mike

**Comment by HuangWen92** [comment]
The q is a big prime number. In particular, it is D227367BFF624F42C92797D1A1A32BBD4238E0F60CAAC4B46F49F46542721331239A4744D95F28C26C99F2DDA763E9771E728DAC128A0EA48E46B7337B40805D
![image](https://user-images.githubusercontent.com/5373633/103172701-36fd6a00-4890-11eb-92f6-0456be0ffdcc.png)

for (int i = 0; i < 1000; i++) {
		big num1 = mirvar(0);
		big num2 = mirvar(0);
		big num3 = mirvar(0);
		big num4 = mirvar(0);
		bigrand(q,num1);
		bigrand(q, num2);
		mip->IOBASE = 16;
		mr_xor(num1, num2, num3);
		mr_xor(num3, num2, num4); 
		printf("the i:%d\n",i);

		if (fcomp(num1, num4) != 0) {
			printf(" there is an error in xor\n");
			cotnum(q, stdout);
		}
			   
	}

**Comment by mcarrickscott** [comment]
This works for me

#include <stdio.h>
#include "miracl.h"

int main()
{
    int i;
    miracl *mip=mirsys(200,16);
    big q=mirvar(0);

    mip->IOBASE=16;

cinstr(q,"D227367BFF624F42C92797D1A1A32BBD4238E0F60CAAC4B46F49F46542721331239A4744D95F28C26C99F2DDA763E9771E728DAC128A0EA48E46B7337B40805D");
    printf("q= ");cotnum(q,stdout);printf("\n");
    for (i = 0; i < 1000; i++) {
        big num1 = mirvar(0);
        big num2 = mirvar(0);
        big num3 = mirvar(0);
        big num4 = mirvar(0);
        bigrand(q,num1);
        bigrand(q, num2);
        mr_xor(num1, num2, num3);
        mr_xor(num3, num2, num4);
        printf("the i:%d\n",i);
        if (fcomp(num1, num4) != 0)printf(" there is an error in xor\n");
    }
}

Mike

**Comment by HuangWen92** [comment]
Thank you very much for your precious time. I find the problem and know how to fix it. 
 I used the sentence "miracl *mip=mirsys(1000,10)", not miracl *mip=mirsys(200,16).
You can reproduce it by following code, If you are still interested in the phenomenon.

int i;
mip =  mirsys(10000, 10);
mip->IOBASE = 16;
big q = mirvar(0);

cinstr(q, "D227367BFF624F42C92797D1A1A32BBD4238E0F60CAAC4B46F49F46542721331239A4744D95F28C26C99F2DDA763E9771E728DAC128A0EA48E46B7337B40805D");
printf("q= "); cotnum(q, stdout); printf("\n");
for (i = 0; i < 1000; i++) {
	big num1 = mirvar(0);
	big num2 = mirvar(0);
	big num3 = mirvar(0);
	big num4 = mirvar(0);
	bigrand(q, num1);
	bigrand(q, num2);
	mr_xor(num1, num2, num3);
	mr_xor(num3, num2, num4);
	printf("the i:%d\n", i);
	if (fcomp(num1, num4) != 0)printf(" there is an error in xor\n");
}
